version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ronpai-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"  # PHP-FPMのポートを外部に公開
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ronpai-db
    environment:
      MYSQL_DATABASE: ronpai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ronpai
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: ronpai-nginx
    ports:
      - "80:80"  # Nginxのポートを公開
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/public:/var/www/html/public
    depends_on:
      - app

volumes:
  db-data:
